### ISSUE TITLE
mstpr-brainbot - Malicious user can take advantage of unset minimumAssets values

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#12]
mstpr-brainbot

medium

# Malicious user can take advantage of unset minimumAssets values

## Summary
Users can take advantage of the not setted minimumAssets by DOS'ing the queue or lowering the fee after a successful fulfilled order.
## Vulnerability Detail
When a new pool added by the owner, the minimumAssets is not enforced to set. Minimum amount originally always blocks 0 amount deposits. However, if it's not set a user can take advantage of this by creating minimal orders. This would not only DOS the queue but the fee that the user pays will also be lower. A user can create multiple accounts and deposit the bear minimum which is usually 10001 due to the minAmountOut calculation in the _addPosition since 0 amount liquidity adding is forbidden in univ3.

This is how the fee is calculated for users when they claim their position:
`newClaim.feePerUser = uint128(estimatedFee / totalUsers); `

if user can increase the totalUsers to a big number, user can lower down the fee.

Scenario: Assume the minimumAmounts are not set for the token LUSD. Bob created an order and he is the only one in that order. 
Bob assumes the `estimatedFee` which is `uint256(upkeepGasLimit * getGasPrice())` will be 0.1 ETH. 
Bob adds 10001 LUSD with 10 different accounts to the same tick position. 10001 LUSD is a very very low number since LUSD has 18 decimals so Bob can do this almost free. Now, when Bobs' order fulfills via a successful performUpkeep, Bob will pay 

0.1 / 10 = 0.01 ETH. Which means Bob paid 10x lower fee than he should have. 
## Impact
Although this can easily prevented by the owner by setting the minimumAssets in the same tx with registering the token, I classified this as a medium finding since the owner is RESTRICTED. I think this should be enforced when a new pool is registered.
## Code Snippet
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1215-L1248

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1256-L1261
## Tool used

Manual Review

## Recommendation
When registering the pool, also set the minimumAssets amounts for both of the tokens. 

Duplicate of #49

**Comment by mstpr** [comment]
Escalate for 10 USDC

This is almost as same as this one #49 and it should be a duplicate 

Both issues are explaining the same root issue where users adding dummy addresses to divide the fee. However, as #49 also states this can be avoided if the minimumAssetValue is set to a decent level where it's not profitable for users to dilute the fee. The assumption 49 makes is that the minimumAssetValue is set to a small number which is the only case where this type of "attack" is possible. Here in this issue I was mainly focusing on the importance of the minimumAssetValue because it is only feasible to perform the attack if this condition is set. Overall both of the issues are explaining the same thing so this one should be a dup of #49

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> This is almost as same as this one #49 and it should be a duplicate 
> 
> Both issues are explaining the same root issue where users adding dummy addresses to divide the fee. However, as #49 also states this can be avoided if the minimumAssetValue is set to a decent level where it's not profitable for users to dilute the fee. The assumption 49 makes is that the minimumAssetValue is set to a small number which is the only case where this type of "attack" is possible. Here in this issue I was mainly focusing on the importance of the minimumAssetValue because it is only feasible to perform the attack if this condition is set. Overall both of the issues are explaining the same thing so this one should be a dup of #49 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #49 
The final severity of the issue will depend on the resolution of issue #49

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/12/#issuecomment-1648461105): accepted
