### ISSUE TITLE
p0wd3r - If the request for registerUpkeep is set to pending status, the protocol functionality will be disabled.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#13]
p0wd3r

high

# If the request for registerUpkeep is set to pending status, the protocol functionality will be disabled.

## Summary
If the request for `registerUpkeep` is set to pending status, the protocol functionality will be disabled.
## Vulnerability Detail
In the `registerUpkeep` function of Chainlink, it will determine whether to set the request as pending based on the configuration of the registrar. Additionally, only the owner of the registrar can approve pending requests.

https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/2_0/KeeperRegistrar2_0.sol#L371-L382
```solidity
    uint256 upkeepId;
    RegistrarConfig memory config = s_config;
    if (_shouldAutoApprove(config, sender)) {
      s_config.approvedCount = config.approvedCount + 1;

      upkeepId = _approve(params, hash);
    } else {
      uint96 newBalance = s_pendingRequests[hash].balance + params.amount;
      s_pendingRequests[hash] = PendingRequest({admin: params.adminAddress, balance: newBalance});
    }

    return upkeepId;
```

https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/2_0/KeeperRegistrar2_0.sol#L188-L219
```solidity
  ) external onlyOwner {
    PendingRequest memory request = s_pendingRequests[hash];
    if (request.admin == address(0)) {
      revert RequestNotFound();
    }
    bytes32 expectedHash = keccak256(abi.encode(upkeepContract, gasLimit, adminAddress, checkData, offchainConfig));
    if (hash != expectedHash) {
      revert HashMismatch();
    }
    delete s_pendingRequests[hash];
    _approve(
```

In the `setupLimitOrder` of GFX, there is no check whether the return value of `registerUpkeep` is 0.

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L417-L428
```solidity
                ERC20(address(LINK)).safeApprove(address(registrar), initialUpkeepFunds);
                RegistrationParams memory params = RegistrationParams({
                    name: "Limit Order Registry",
                    encryptedEmail: abi.encode(0),
                    upkeepContract: address(this),
                    gasLimit: uint32(maxFillsPerUpkeep * upkeepGasLimit),
                    adminAddress: owner,
                    checkData: abi.encode(pool),
                    offchainConfig: abi.encode(0),
                    amount: uint96(initialUpkeepFunds)
                });
                registrar.registerUpkeep(params);
```

Therefore, even if the request enters the pending state, it can still be completed setup.
This may lead to the following scenarios:
1. Owner executes setUp, putting the request into pending status.
2. User creates an order.
3. The price has reached the user's target price, but the upkeep is still in a pending state, resulting in the automation not triggering properly and the transaction unable to be executed. The user has suffered losses.
## Impact
The order cannot be completed successfully, causing losses to the user.
## Code Snippet
- https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/2_0/KeeperRegistrar2_0.sol#L371-L382
- https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/2_0/KeeperRegistrar2_0.sol#L188-L219
- https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L417-L428
## Tool used

Manual Review

## Recommendation
Check the return value of `registerUpkeep`, if it is 0 then revert.

**Comment by imp0wd3r** [comment]
Escalate

The note from Lead Judge is as follows https://docs.google.com/spreadsheets/d/1GG-0N1tKLdrOBpVpIkIZQarFLoDOAPlksytHlrCGARQ/edit#gid=0
> I don't see why we need to check keeperId

If keeperId is 0, it means that this upkeep is in pending status and will not take effect immediately. 
https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/2_0/KeeperRegistrar2_0.sol#L175-L183
```solidity
  function registerUpkeep(RegistrationParams calldata requestParams) external returns (uint256) {
    if (requestParams.amount < s_config.minLINKJuels) {
      revert InsufficientPayment();
    }

    LINK.transferFrom(msg.sender, address(this), requestParams.amount);

    return _register(requestParams, msg.sender);
  }
```

https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/2_0/KeeperRegistrar2_0.sol#L371-L382
```solidity
function _register(RegistrationParams memory params, address sender) private returns (uint256) {
...
    uint256 upkeepId;
    RegistrarConfig memory config = s_config;
    if (_shouldAutoApprove(config, sender)) {
      s_config.approvedCount = config.approvedCount + 1;

      upkeepId = _approve(params, hash);
    } else {
      uint96 newBalance = s_pendingRequests[hash].balance + params.amount;
      s_pendingRequests[hash] = PendingRequest({admin: params.adminAddress, balance: newBalance});
    }

    return upkeepId;
}
```

Due to the fact that the execution of limit orders is triggered by upkeep, if the upkeep is in a pending state, the processing of orders will not be triggered normally, resulting in the failure of protocol functionality.

**Furthermore, a key point is that the registrar is not under the control of the project team. It is controlled by Chainlink. Therefore, the project team needs to check whether the registrar is in an autoApprove state.**
- https://docs.chain.link/chainlink-automation/supported-networks/#configurations
- https://etherscan.io/address/0x02777053d6764996e594c3E88AF1D58D5363a2e6#code
- https://etherscan.io/address/0xDb8e8e2ccb5C033938736aa89Fe4fa1eDfD15a1d#code

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> The note from Lead Judge is as follows https://docs.google.com/spreadsheets/d/1GG-0N1tKLdrOBpVpIkIZQarFLoDOAPlksytHlrCGARQ/edit#gid=0
> > I don't see why we need to check keeperId
> 
> If keeperId is 0, it means that this upkeep is in pending status and will not take effect immediately. 
> https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/2_0/KeeperRegistrar2_0.sol#L175-L183
> ```solidity
>   function registerUpkeep(RegistrationParams calldata requestParams) external returns (uint256) {
>     if (requestParams.amount < s_config.minLINKJuels) {
>       revert InsufficientPayment();
>     }
> 
>     LINK.transferFrom(msg.sender, address(this), requestParams.amount);
> 
>     return _register(requestParams, msg.sender);
>   }
> ```
> 
> https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/2_0/KeeperRegistrar2_0.sol#L371-L382
> ```solidity
> function _register(RegistrationParams memory params, address sender) private returns (uint256) {
> ...
>     uint256 upkeepId;
>     RegistrarConfig memory config = s_config;
>     if (_shouldAutoApprove(config, sender)) {
>       s_config.approvedCount = config.approvedCount + 1;
> 
>       upkeepId = _approve(params, hash);
>     } else {
>       uint96 newBalance = s_pendingRequests[hash].balance + params.amount;
>       s_pendingRequests[hash] = PendingRequest({admin: params.adminAddress, balance: newBalance});
>     }
> 
>     return upkeepId;
> }
> ```
> 
> Due to the fact that the execution of limit orders is triggered by upkeep, if the upkeep is in a pending state, the processing of orders will not be triggered normally, resulting in the failure of protocol functionality.
> 
> **Furthermore, a key point is that the registrar is not under the control of the project team. It is controlled by Chainlink. Therefore, the project team needs to check whether the registrar is in an autoApprove state.**
> - https://docs.chain.link/chainlink-automation/supported-networks/#configurations
> - https://etherscan.io/address/0x02777053d6764996e594c3E88AF1D58D5363a2e6#code
> - https://etherscan.io/address/0xDb8e8e2ccb5C033938736aa89Fe4fa1eDfD15a1d#code

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
Escalate for 10 USDC

The root cause mentioned in this report is that the upkeeps might still be in a "pending" state after registration because the owner of the registrar needs to approve the pending requests.

As I understand from the sponsor, they are using Chainlink v1.2 right now and are planning to upgrade to a newer version. The following is extracted from the https://docs.chain.link/chainlink-automation/automation-release-notes#2022-08-04---v12-release,

> **Automatic upkeep registration approval**: All upkeeps on mainnet are now automatically approved **Programmatic control**: With automatic approval, you can now dynamically create, manage, and fund upkeeps from within your dApps and even have an upkeep fund itself.

As long as they are using v1.2 and above and deployed on mainnet, not testnet, the upkeep can be dynamically created and automatically approved. So it is not true that it requires approval from the registrar owner to finalize the upkeep registration.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> The root cause mentioned in this report is that the upkeeps might still be in a "pending" state after registration because the owner of the registrar needs to approve the pending requests.
> 
> As I understand from the sponsor, they are using Chainlink v1.2 right now and are planning to upgrade to a newer version. The following is extracted from the https://docs.chain.link/chainlink-automation/automation-release-notes#2022-08-04---v12-release,
> 
> > **Automatic upkeep registration approval**: All upkeeps on mainnet are now automatically approved **Programmatic control**: With automatic approval, you can now dynamically create, manage, and fund upkeeps from within your dApps and even have an upkeep fund itself.
> 
> As long as they are using v1.2 and above and deployed on mainnet, not testnet, the upkeep can be dynamically created and automatically approved. So it is not true that it requires approval from the registrar owner to finalize the upkeep registration.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by imp0wd3r** [comment]
> Escalate for 10 USDC
> 
> The root cause mentioned in this report is that the upkeeps might still be in a "pending" state after registration because the owner of the registrar needs to approve the pending requests.
> 
> As I understand from the sponsor, they are using Chainlink v1.2 right now and are planning to upgrade to a newer version. The following is extracted from the https://docs.chain.link/chainlink-automation/automation-release-notes#2022-08-04---v12-release,
> 
> > **Automatic upkeep registration approval**: All upkeeps on mainnet are now automatically approved **Programmatic control**: With automatic approval, you can now dynamically create, manage, and fund upkeeps from within your dApps and even have an upkeep fund itself.
> 
> As long as they are using v1.2 and above and deployed on mainnet, not testnet, the upkeep can be dynamically created and automatically approved. So it is not true that it requires approval from the registrar owner to finalize the upkeep registration.

I think the key issue lies in the fact that `autoApprove` is configurable by the chainlink owner through the contract, and we cannot assume it will remain unchanged. If the configuration is changed, our contract will not be able to detect it.

https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/2_0/KeeperRegistrar2_0.sol#L249-L265

```solidity
  function setRegistrationConfig(
    AutoApproveType autoApproveConfigType,
    uint16 autoApproveMaxAllowed,
    address keeperRegistry,
    uint96 minLINKJuels
  ) public onlyOwner {
    uint32 approvedCount = s_config.approvedCount;
    s_config = RegistrarConfig({
      autoApproveConfigType: autoApproveConfigType,
      autoApproveMaxAllowed: autoApproveMaxAllowed,
      approvedCount: approvedCount,
      minLINKJuels: minLINKJuels,
      keeperRegistry: AutomationRegistryBaseInterface(keeperRegistry)
    });

    emit ConfigChanged(autoApproveConfigType, autoApproveMaxAllowed, keeperRegistry, minLINKJuels);
  }
```

**Comment by hrishibhat** [comment]
@xiaoming9090

**Comment by xiaoming9090** [comment]
@hrishibhat Chainlink has already enabled the auto-approval and announced it publicly. It is unlikely that Chainlink will disable auto-approval in the future because it will break all protocols on the blockchains that rely on this feature to function correctly, which is quite an irresponsible action.
Also, the actions of an external 3rd party dependency (e.g., Chainlink) are out-of-scope of the Sherlock contest.

**Comment by hrishibhat** [comment]
@imp0wd3r I think it is fair that this is a low issue based on the above comments.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/13/#issuecomment-1651004102): accepted
- [imp0wd3r](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/13/#issuecomment-1648833436): rejected
