### ISSUE TITLE
mstpr-brainbot - If the token has 0-2 decimals user can get sandwitched

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#25]
mstpr-brainbot

medium

# If the token has 0-2 decimals user can get sandwitched

## Vulnerability Detail
Since the contract should be adaptable with every univ3 tokens, there is an edge case with the 2 decimal tokens. When liquidity is added to the position the minimumOut is calculated as follows:

```solidity
uint128 amount0Min = amount0 == 0 ? 0 : (amount0 * 0.9999e4) / 1e4;
uint128 amount1Min = amount1 == 0 ? 0 : (amount1 * 0.9999e4) / 1e4;
```

if the token0 has 2 decimals and users adds liquidity with that token with an amount0 of 1000 (10 tokens with 2 decimal precision),  amount0Min will be calculated as 0 due to division truncates the result towards zero. If the amount0Min is 0 Sandwitch attack threads will be viable for this operation.
## Code Snippet
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1215-L1241
## Tool used

Manual Review

**Comment by mstpr** [comment]
Escalate for 10 USDC

I think this is a valid medium. This is an edge case for some exotic tokens. However, the scope says "any Univ3 tokens" which there are many tokens like that in the univ3. In that case the minimum amounts will be calculated as 0 which is frontrunnable and unintended behaviour

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> I think this is a valid medium. This is an edge case for some exotic tokens. However, the scope says "any Univ3 tokens" which there are many tokens like that in the univ3. In that case the minimum amounts will be calculated as 0 which is frontrunnable and unintended behaviour.
> 
> Excell sheet states that this is the same finding as the Cyfrin 6.1.1. However, that issue is indicating an underflow possibility when casting uint128->uint256. In this finding the case is the math rounding to 0 and front-running in result. 

    You've deleted an escalation for this issue.

**Comment by xiaoming9090** [comment]
Escalate for 10 USDC

1) This is an extreme edge case where the ERC20 tokens have a decimal between 0 to 2. Tokens with extremely low decimals are bound to face rounding issues due to how Solidity math is performed, and those tokens are a bad fit in the first place. 

2) Realistically, there are no Uniswap V3 pools that contain an exotic token with a decimal between 0 to 2 that has a decent TVL, as far as I'm aware.

3. The example in the report is incorrect. It mentioned the following:

> if the token0 has 2 decimals and users adds liquidity with that token with an amount0 of 1000 (10 tokens with 2 decimal precision), amount0Min will be calculated as 0 due to division truncates the result towards zero. 

Plugging in the values from the example, it does not round down to zero.

```
uint128 amount0Min = amount0 == 0 ? 0 : (amount0 * 0.9999e4) / 1e4;
(amount0 * 0.9999e4) / 1e4
(1000 * 0.9999e4) / 1e4
9,999,000 / 1e4 = 999.9 = 999
```

When `amount0` is 1000, it round down to 999. When `amount0` is 100, it round down to 99. When `amount0` is 10, it round down to 9. When `amount0` is 2, it round down to `1`. Only when `amount0` is 1, it round down to zero.

It is unlikely that anyone would perform a sandwich attack to obtain 1 WEI of a token in the real world.

4. The report lacks a summary, impact, and recommendation. Thus, it might not even be applicable for a reward as it does not conform to the reporting requirements.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> 1) This is an extreme edge case where the ERC20 tokens have a decimal between 0 to 2. Tokens with extremely low decimals are bound to face rounding issues due to how Solidity math is performed, and those tokens are a bad fit in the first place. 
> 
> 2) Realistically, there are no Uniswap V3 pools that contain an exotic token with a decimal between 0 to 2 that has a decent TVL, as far as I'm aware.
> 
> 3. The example in the report is incorrect. It mentioned the following:
> 
> > if the token0 has 2 decimals and users adds liquidity with that token with an amount0 of 1000 (10 tokens with 2 decimal precision), amount0Min will be calculated as 0 due to division truncates the result towards zero. 
> 
> Plugging in the values from the example, it does not round down to zero.
> 
> ```
> uint128 amount0Min = amount0 == 0 ? 0 : (amount0 * 0.9999e4) / 1e4;
> (amount0 * 0.9999e4) / 1e4
> (1000 * 0.9999e4) / 1e4
> 9,999,000 / 1e4 = 999.9 = 999
> ```
> 
> When `amount0` is 1000, it round down to 999. When `amount0` is 100, it round down to 99. When `amount0` is 10, it round down to 9. When `amount0` is 2, it round down to `1`. Only when `amount0` is 1, it round down to zero.
> 
> It is unlikely that anyone would perform a sandwich attack to obtain 1 WEI of a token in the real world.
> 
> 4. The report lacks a summary, impact, and recommendation. Thus, it might not even be applicable for a reward as it does not conform to the reporting requirements.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mstpr** [comment]
@xiaoming9090 You are correct again, I did the math wrongly. Thank you for correcting here, appreciate it! 

will remove the escalation. Sorry for stealing your time!

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above explanation

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/25/#issuecomment-1651216299): accepted
