### ISSUE TITLE
mstpr-brainbot - Users may not cancel their orders if order goes ITM and back to OTM

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#27]
mstpr-brainbot

medium

# Users may not cancel their orders if order goes ITM and back to OTM

## Summary
An order (OTM) can go to ITM and back to OTM without keepers noticing. In this case, cancelling the OTM order is impossible.
## Vulnerability Detail
When an order is OTM it can go ITM and then back to OTM in a same block. Keepers are checking the checkUpkeep every block or so, they are not checking specific tx. If an order goes ITM and OTM back, there will be some fees accrued to that position in both assets. If the user tries to cancel the quote user will fail due to these lines 

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L854-L862
## Code Snippet
https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L750-L863
## Tool used

Manual Review

**Comment by mstpr** [comment]
Escalate for 10 USDC

This is a valid finding. When the order goes ITM and back to OTM user can't cancel the order because of the require checks since the fee will be accrued to both of the tokens.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> This is a valid finding. When the order goes ITM and back to OTM user can't cancel the order because of the require checks since the fee will be accrued to both of the tokens. 
> 
> To answer @elee1766, when the order is cancelled the code checks only amount0 or amount1 can be returned to user assuming that the order is not fulfilled it makes sense that user should only have either one of the tokens. However, if the order goes through ITM and back to OTM quickly that means there will be fees accrued on the position such that both amount0 and amount1 will not be 0. That means user can't cancel this order anymore. User needs to wait for the order to go back to ITM so someone can call performUpkeep and fulfill the order completely. 

    You've deleted an escalation for this issue.

**Comment by xiaoming9090** [comment]
Escalate for 10 USDC

The value of the `amount0` and `amount1` are obtained [here,](https://github.com/sherlock-audit/2023-06-gfx/blob/59a83c6423834b9173b9c063ec1e505c5d9f1bbb/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1365C16-L1365C16) and the values returned from the `POSITION_MANAGER.decreaseLiquidity` function do not include fees.

```
(uint256 a0, uint256 a1) = POSITION_MANAGER.decreaseLiquidity(params);
// downcast to uint128 since those are the units we use
amount0 = uint128(a0);
amount1 = uint128(a1);
```

The fee accrued will be collected via the ` POSITION_MANAGER.collect` function and sent to the owner separately.

As such, the `amount0` and `amount1` below do not include fees and will operate fine even if the order goes ITM and back to OTM. Thus, this issue is invalid.

https://github.com/sherlock-audit/2023-06-gfx/blob/59a83c6423834b9173b9c063ec1e505c5d9f1bbb/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L854
```solidity
if (order.direction) {
    if (amount0 > 0) poolToData[pool].token0.safeTransfer(sender, amount0);
    else revert LimitOrderRegistry__NoLiquidityInOrder();
    if (amount1 > 0) revert LimitOrderRegistry__AmountShouldBeZero();
} else {
    if (amount1 > 0) poolToData[pool].token1.safeTransfer(sender, amount1);
    else revert LimitOrderRegistry__NoLiquidityInOrder();
    if (amount0 > 0) revert LimitOrderRegistry__AmountShouldBeZero();
}
```

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> The value of the `amount0` and `amount1` are obtained [here,](https://github.com/sherlock-audit/2023-06-gfx/blob/59a83c6423834b9173b9c063ec1e505c5d9f1bbb/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1365C16-L1365C16) and the values returned from the `POSITION_MANAGER.decreaseLiquidity` function do not include fees.
> 
> ```
> (uint256 a0, uint256 a1) = POSITION_MANAGER.decreaseLiquidity(params);
> // downcast to uint128 since those are the units we use
> amount0 = uint128(a0);
> amount1 = uint128(a1);
> ```
> 
> The fee accrued will be collected via the ` POSITION_MANAGER.collect` function and sent to the owner separately.
> 
> As such, the `amount0` and `amount1` below do not include fees and will operate fine even if the order goes ITM and back to OTM. Thus, this issue is invalid.
> 
> ```solidity
> if (order.direction) {
>     if (amount0 > 0) poolToData[pool].token0.safeTransfer(sender, amount0);
>     else revert LimitOrderRegistry__NoLiquidityInOrder();
>     if (amount1 > 0) revert LimitOrderRegistry__AmountShouldBeZero();
> } else {
>     if (amount1 > 0) poolToData[pool].token1.safeTransfer(sender, amount1);
>     else revert LimitOrderRegistry__NoLiquidityInOrder();
>     if (amount0 > 0) revert LimitOrderRegistry__AmountShouldBeZero();
> }
> ```

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mstpr** [comment]
@xiaoming9090 That's correct sorry for this one thanks for the explanation. The return variables of decreaseLiquidity indeed not involves the fee my bad. Thanks! 

I'll remove my escalation

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above explanation.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [xiaoming9090](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/27/#issuecomment-1651421633): accepted
