### ISSUE TITLE
p0wd3r - fastGasFeed's answer should check if it is greater than MAX_GAS_PRICE.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#4]
p0wd3r

medium

# fastGasFeed's answer should check if it is greater than MAX_GAS_PRICE.

## Summary
`fastGasFeed`'s answer should check if it is greater than `MAX_GAS_PRICE`.
## Vulnerability Detail
First of all, the owner is restricted, which means that the actions of the owner need to be constrained.

> Q: Is the admin/owner of the protocol/contracts TRUSTED or RESTRICTED?
> restricted. the owner should not be able to steal funds.

Owner can set the address of `fastGasFeed`, which is used to obtain gas price.

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L482-L484
```solidity
    function setFastGasFeed(address feed) external onlyOwner {
        fastGasFeed = feed;
    }
```

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1447-L1465
```solidity
    function getGasPrice() public view returns (uint256) {
        // If gas feed is set use it.
        if (fastGasFeed != address(0)) {
            (, int256 _answer, , uint256 _timestamp, ) = IChainlinkAggregator(fastGasFeed).latestRoundData();
            uint256 timeSinceLastUpdate = block.timestamp - _timestamp;
            // Check answer is not stale.
            if (timeSinceLastUpdate > FAST_GAS_HEARTBEAT) {
                // If answer is stale use owner set value.
                // Multiply by 1e9 to convert gas price to gwei
                return uint256(upkeepGasPrice) * 1e9;
            } else {
                // Else use the datafeed value.
                uint256 answer = uint256(_answer);
                return answer;
            }
        }
        // Else use owner set value.
        return uint256(upkeepGasPrice) * 1e9; // Multiply by 1e9 to convert gas price to gwei
    }
```

As a fallback solution for gas price, `upkeepGasPrice` is restricted from exceeding `MAX_GAS_PRICE`.

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L471-L475
```solidity
    function setUpkeepGasPrice(uint32 gasPrice) external onlyOwner {
        // should revert if the gas price provided is greater than the provided max gas price.
        if (gasPrice > MAX_GAS_PRICE) revert LimitOrderRegistry__InvalidGasPrice();
        upkeepGasPrice = gasPrice;
    }
```

But as the owner, there are no restrictions on the arbitrarily controllable `fastGasFeed` answer.

## Impact
Owner can set gas price arbitrarily, excessively high gas prices prevent users from claiming and cause a DoS on the protocol's functionality.
## Code Snippet
- https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L482-L484
- https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L1447-L1465
- https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L471-L475
## Tool used

Manual Review

## Recommendation
`fastGasFeed`'s answer should check if it is greater than `MAX_GAS_PRICE`.

Duplicate of #54

**Comment by imp0wd3r** [comment]
Escalate

This vulnerability is same with Method 2 in https://github.com/sherlock-audit/2023-06-gfx-judging/issues/54.

Same as this vulnerability https://github.com/sherlock-audit/2023-06-gfx-judging/issues/21

Furthermore, the lead judge's markings for this vulnerability can be found at https://docs.google.com/spreadsheets/d/1GG-0N1tKLdrOBpVpIkIZQarFLoDOAPlksytHlrCGARQ/edit#gid=0.
> fastGasFeed is address. You suggest to check whether the value is greater than the address

This is incorrect. It's not about checking the value of `fastGasFeed`, but rather checking the answer obtained through it: `(, int256 _answer, , uint256 _timestamp, ) = IChainlinkAggregator(fastGasFeed).latestRoundData();`

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This vulnerability is same with Method 2 in https://github.com/sherlock-audit/2023-06-gfx-judging/issues/54.
> 
> Same as this vulnerability https://github.com/sherlock-audit/2023-06-gfx-judging/issues/21
> 
> Furthermore, the lead judge's markings for this vulnerability can be found at https://docs.google.com/spreadsheets/d/1GG-0N1tKLdrOBpVpIkIZQarFLoDOAPlksytHlrCGARQ/edit#gid=0.
> > fastGasFeed is address. You suggest to check whether the value is greater than the address
> 
> This is incorrect. It's not about checking the value of `fastGasFeed`, but rather checking the answer obtained through it: `(, int256 _answer, , uint256 _timestamp, ) = IChainlinkAggregator(fastGasFeed).latestRoundData();`

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #54

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imp0wd3r](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/4/#issuecomment-1648821126): accepted
