### ISSUE TITLE
mstpr-brainbot - Owner can take advantage of the keeper contracts functions to harm users

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-gfx-judging#8]
mstpr-brainbot

medium

# Owner can take advantage of the keeper contracts functions to harm users

## Summary
Owner can call few functions in keeper registry to harm users.
## Vulnerability Detail
The owner of the upkeep job in keeper registry is the owner of the LimitOrderRegistry. There are some functions that are crucial for the healthy maintenance of the LimitOrderRegistry contract. If owner is malicious, owner can cancel the upkeep for a pool that would make that pools keepers to not work. What's worse is that it is not possible to re-register the pool to upkeep because of these lines

https://github.com/sherlock-audit/2023-06-gfx/blob/main/uniswap-v3-limit-orders/src/LimitOrderRegistry.sol#L393
 
## Impact

Although the owner can't really steal the funds from users directly, owner can mess with the keeper settings. If owner manages to deactivate all the upkeep jobs the fees that owner takes when user claims is basically a stolen fund since the keeper service is permanently closed.

There are bunch of keeper functions that owner can take advantage to harm users. I don't want to put single issues for all of them so I'll list the potential dangerous functions for owner to call to harm the users. 

## Code Snippet
Functions in keeper contract that owner can take advantage

https://github.com/smartcontractkit/chainlink/blob/1ec921f4aa288dbdd7e67df151b4adc8b4a339eb/contracts/src/v0.8/automation/2_0/KeeperRegistryLogic2_0.sol#L176-L205

https://github.com/smartcontractkit/chainlink/blob/1ec921f4aa288dbdd7e67df151b4adc8b4a339eb/contracts/src/v0.8/automation/2_0/KeeperRegistryLogic2_0.sol#L223-L256

https://github.com/smartcontractkit/chainlink/blob/1ec921f4aa288dbdd7e67df151b4adc8b4a339eb/contracts/src/v0.8/automation/2_0/KeeperRegistryLogic2_0.sol#L302-L359
## Tool used

Manual Review

## Recommendation
If the idea of the contract is to provide a fully decentralized and permissionless software, keeper admin functions should be in a contract aswell and there should be some validations on how owner can calls them.

**Comment by mstpr** [comment]
Escalate for 10 USDC

I think this is valid medium. Imagine where there are 50 orders that are near OTM. Owner cancels the upkeep, now users need to perform upkeep manually. However, whether the performUpkeep called manually or via chainlink keepers the fee will be taken and sent to the owner. Users are paying the ETH for owner to compensate the gas fee and in this scenario users must call the performUpkeep they own with their ETH and pay the additional fee to owner.

Imagine user has claimable 100$ worth of USDC. The fee is 5$ in ETH and keepers are not working due to malicious owner cancelling the keeper. 
Now this user will call the performUpkeep and will pay the transaction fee (let's assume it is also 5$) and on top of that user will pay the fee to owner which is an another 5$. 

As the owner is restricted, if owner cancels the upkeep then there is no point of using this contract since keeper fees are sent to owner regardless of whoever calls the perform upkeep.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> 
> I think this is valid medium. Imagine where there are 50 orders that are near OTM. Owner cancels the upkeep, now users need to perform upkeep manually. However, whether the performUpkeep called manually or via chainlink keepers the fee will be taken and sent to the owner. Users are paying the ETH for owner to compensate the gas fee and in this scenario users must call the performUpkeep they own with their ETH and pay the additional fee to owner.
> 
> Imagine user has claimable 100$ worth of USDC. The fee is 5$ in ETH and keepers are not working due to malicious owner cancelling the keeper. 
> Now this user will call the performUpkeep and will pay the transaction fee (let's assume it is also 5$) and on top of that user will pay the fee to owner which is an another 5$. 
> 
> As the owner is restricted, if owner cancels the upkeep then there is no point of using this contract since keeper fees are sent to owner regardless of whoever calls the perform upkeep. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
@elee1766

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low issue based on the following comments:
>  because currently we as the owner are subsidizing all of the LINK used for chainlink automation upkeeps, us chosing to no longer subsidize this cost is not a malicious action.
>  the fee charged by the contract is intended to be  the "utility" fee for the convenience of the contract which manages the order for which one can set it up with any automation system.
> using the gas fee as our commission was simply a convenient initial number, but future iterations may calculate this utility fee differently

Agree with the Sponsor comment.
I don't think this can be seen as stealing funds based on Sponsor comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-gfx-judging/issues/8/#issuecomment-1648408813): rejected
